// <auto-generated />
using System;
using AtmSimulator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtmSimulator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AtmSimulator.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 10000m,
                            CreatedAt = new DateTime(2026, 4, 5, 12, 9, 31, 83, DateTimeKind.Utc).AddTicks(1840),
                            OwnerName = "John Jones"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 5000m,
                            CreatedAt = new DateTime(2026, 4, 5, 12, 9, 31, 83, DateTimeKind.Utc).AddTicks(1843),
                            OwnerName = "Will Smith"
                        });
                });

            modelBuilder.Entity("AtmSimulator.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedPinAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            CardNumber = "1234567890123456",
                            ExpiryDate = new DateTime(2029, 4, 5, 12, 9, 31, 83, DateTimeKind.Utc).AddTicks(1970),
                            FailedPinAttempts = 0,
                            IsBlocked = false,
                            PinHash = "1234"
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            CardNumber = "6543210987654321",
                            ExpiryDate = new DateTime(2029, 4, 5, 12, 9, 31, 83, DateTimeKind.Utc).AddTicks(1978),
                            FailedPinAttempts = 0,
                            IsBlocked = false,
                            PinHash = "4321"
                        });
                });

            modelBuilder.Entity("AtmSimulator.Models.CashStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("Denomination")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Denomination")
                        .IsUnique();

                    b.ToTable("CashStorage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 100,
                            Denomination = 500
                        },
                        new
                        {
                            Id = 2,
                            Count = 100,
                            Denomination = 200
                        },
                        new
                        {
                            Id = 3,
                            Count = 100,
                            Denomination = 100
                        },
                        new
                        {
                            Id = 4,
                            Count = 100,
                            Denomination = 50
                        },
                        new
                        {
                            Id = 5,
                            Count = 100,
                            Denomination = 20
                        });
                });

            modelBuilder.Entity("AtmSimulator.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AtmSimulator.Models.Card", b =>
                {
                    b.HasOne("AtmSimulator.Models.Account", "Account")
                        .WithOne("Card")
                        .HasForeignKey("AtmSimulator.Models.Card", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AtmSimulator.Models.Transaction", b =>
                {
                    b.HasOne("AtmSimulator.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AtmSimulator.Models.Account", b =>
                {
                    b.Navigation("Card");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
